baseURL = 'https://kclamalex.github.io/'
languageCode = 'en'
title = "kclamalex"
theme = "hugo-bearcub"
copyright = "Alex Lam (CC BY 4.0)"

[languages]
  [languages.en]
    title = "kclamalex"
    languageName = "en-US 🇺"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      description = ""
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params.author]
name = "Alex Lam"
email = "kclamalex@gmail.com"
